[package]
name = "bullet_stream"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
fun_run = "0.1.2"
indoc = "2.0.5"
tempfile = "3.10.1"
libcnb-test = "0.21.0"
ascii_table = { version = "4.0.3", features = ["color_codes"] }
